#!/bin/bash
betty 0-isupper.c 
betty 0-memset.c 
betty 0-strcat.c 
betty 1-isdigit.c 
betty 1-memcpy.c 
betty 1-strncat.c 
betty 100-atoi.c 
betty 2-strchr.c 
betty 2-strlen.c 
betty 2-strncpy.c 
betty 3-islower.c 
betty 3-puts.c -o 
betty 3-strcmp.c 
betty 3-strspn.c 
betty 4-isalpha.c 
betty 4-strpbrk.c 
betty 5-strstr.c 
betty 6-abs.c 
betty 9-strcpy.c 
betty _putchar.c 
